import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {
  buildDashboardBranchRows, dashboardInventorySummary, dashboardTransferSummary,
  isPostedInMonth, isPostedOn, jakartaBusinessDate, resolveDashboardInventory,
} from "../src/lib/dashboardReadModelCore.js";

const product = (id = "P1", price = 100, minimum = 10) => ({ id, name: id, sku: id, purchase_price: price, min_stock: minimum });
const legacy = (branch = "B1") => [{ id: "L1", branch_id: branch, product_id: "P1", warehouse_id: "W1", quantity: 60 }, { id: "L2", branch_id: branch, product_id: "P1", warehouse_id: "W2", quantity: 40 }];

test("A - legacy stock only resolves 100", () => { const rows = resolveDashboardInventory({ balances: legacy(), products: [product()] }); assert.equal(rows[0].quantity, 100); });
test("B - branch balance 90 overrides legacy 100", () => { const rows = resolveDashboardInventory({ balances: [...legacy(), { id: "B", branch_id: "B1", product_id: "P1", balance_scope: "branch", quantity: 90 }], products: [product()] }); assert.equal(rows[0].quantity, 90); });
test("C - branch 120 is not double counted", () => { const rows = resolveDashboardInventory({ balances: [...legacy(), { id: "B", branch_id: "B1", product_id: "P1", balance_scope: "branch", quantity: 120 }], products: [product()] }); assert.equal(dashboardInventorySummary(rows).quantity, 120); });
test("D - multi branch resolved quantity totals 140", () => { const rows = resolveDashboardInventory({ balances: [{ id: "B1", branch_id: "B1", product_id: "P1", balance_scope: "branch", quantity: 90 }, { id: "B2", branch_id: "B2", product_id: "P1", balance_scope: "branch", quantity: 50 }], products: [product()] }); assert.equal(dashboardInventorySummary(rows).quantity, 140); });
test("E - inventory value uses Inventory resolver unit cost", () => { const rows = resolveDashboardInventory({ balances: [{ id: "B", branch_id: "B1", product_id: "P1", balance_scope: "branch", quantity: 10 }], products: [product("P1", 55000)] }); assert.equal(dashboardInventorySummary(rows).inventory_value, 550000); });
test("F - low stock includes MENIPIS", () => { const rows = resolveDashboardInventory({ balances: [{ id: "B", branch_id: "B1", product_id: "P1", balance_scope: "branch", quantity: 5 }], products: [product()] }); assert.equal(rows[0].status, "MENIPIS"); assert.equal(dashboardInventorySummary(rows).low_stock, 1); });
test("G - operational branch scope excludes another branch", () => { const rows = resolveDashboardInventory({ balances: [{ id: "B1", branch_id: "B1", product_id: "P1", balance_scope: "branch", quantity: 10 }, { id: "B2", branch_id: "B2", product_id: "P1", balance_scope: "branch", quantity: 20 }], products: [product()], branchIds: ["B1"] }); assert.deepEqual(rows.map((row) => row.branch_id), ["B1"]); });
test("H - Head Office aggregates branches after per-branch resolution", () => { const balances = [...legacy("B1"), { id: "B", branch_id: "B1", product_id: "P1", balance_scope: "branch", quantity: 90 }, { id: "M", branch_id: "B2", product_id: "P1", balance_scope: "branch", quantity: 50 }]; assert.equal(dashboardInventorySummary(resolveDashboardInventory({ balances, products: [product()] })).quantity, 140); });
test("I - today uses Asia Jakarta at UTC boundary", () => { assert.equal(jakartaBusinessDate("2026-08-14T20:00:00.000Z"), "2026-08-15"); assert.equal(isPostedOn({ status: "posted", date: "2026-08-14T20:00:00.000Z" }, "2026-08-15"), true); });
test("J - draft sale is excluded from final KPI", () => { assert.equal(isPostedInMonth({ status: "draft", date: "2026-08-14" }, "2026-08"), false); });
test("K - draft purchase is excluded from final KPI", () => { assert.equal(isPostedOn({ status: "draft", date: "2026-08-14" }, "2026-08-14"), false); });
test("L - approved transfer enters transit KPI", () => { const summary = dashboardTransferSummary([{ status: "approved", source_branch_id: "B1", destination_branch_id: "B2", items: [{ in_transit_qty: 20 }] }]); assert.deepEqual([summary.transit_count, summary.transit_qty], [1, 20]); });
test("M - received transfer leaves transit KPI", () => { const summary = dashboardTransferSummary([{ status: "received", source_branch_id: "B1", destination_branch_id: "B2", items: [{ in_transit_qty: 0 }] }]); assert.deepEqual([summary.transit_count, summary.transit_qty], [0, 0]); });
test("N/O - Dashboard has no forbidden lifecycle or storage-location dependency", () => { for (const file of ["../src/pages/Dashboard.jsx", "../src/pages/HeadOfficeDashboard.jsx"]) { const source = fs.readFileSync(new URL(file, import.meta.url), "utf8"); assert.doesNotMatch(source, /shipped/i); assert.doesNotMatch(source, /warehouse|gudang/i); } });
test("Head Office branch control rows retain location identity", () => { const inventory = resolveDashboardInventory({ balances: [{ id: "1", branch_id: "B1", product_id: "P1", balance_scope: "branch", quantity: 5 }, { id: "2", branch_id: "B2", product_id: "P1", balance_scope: "branch", quantity: 20 }], products: [product()] }); const rows = buildDashboardBranchRows({ branches: [{ id: "B1", name: "Patrang" }, { id: "B2", name: "Mastrip" }], inventory, today: "2026-08-14" }); assert.deepEqual(rows.map((row) => [row.id, row.inventory_value, row.low_stock]), [["B1", 500, 1], ["B2", 2000, 0]]); });
test("dashboard backend paginates and fails instead of silent truncation", () => { const source = fs.readFileSync(new URL("../base44/functions/getDashboardData/entry.ts", import.meta.url), "utf8"); assert.match(source, /page \* PAGE_SIZE/); assert.match(source, /DASHBOARD_DATA_LIMIT/); });
