import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { approveTransfer, deleteTransferDraft, receiveTransfer, saveTransferDraft, TransferError } from "../base44/shared/stockTransferCore.ts";
import { buildBranchStockReadModel } from "../src/lib/branchStockLedgerCore.js";

function database(seed = {}) {
  let sequence = 0;
  const stores = Object.fromEntries(Object.entries(seed).map(([name, rows]) => [name, rows.map((row) => ({ ...row, items: row.items?.map((item) => ({ ...item })) }))]));
  return new Proxy({ __stores: stores }, { get(target, name) {
    if (name in target) return target[name]; const rows = stores[name] ||= [];
    return {
      async filter(query) { return rows.filter((row) => Object.entries(query).every(([key, value]) => row[key] === value)).map((row) => ({ ...row, items: row.items?.map((item) => ({ ...item })) })); },
      async list() { return rows.map((row) => ({ ...row })); },
      async create(data) { const row = { ...data, items: data.items?.map((item) => ({ ...item })), id: `${String(name)}-${++sequence}`, created_date: `2026-08-14T00:00:${String(sequence).padStart(2, "0")}Z` }; rows.push(row); return { ...row, items: row.items?.map((item) => ({ ...item })) }; },
      async update(id, data) { const row = rows.find((item) => item.id === id); if (!row) throw new Error(`Missing ${String(name)} ${id}`); Object.assign(row, data, data.items ? { items: data.items.map((item) => ({ ...item })) } : {}); return { ...row, items: row.items?.map((item) => ({ ...item })) }; },
      async delete(id) { const index = rows.findIndex((item) => item.id === id); if (index >= 0) rows.splice(index, 1); return { success: true }; },
    };
  }});
}

const sourceUser = { id: "U1", default_branch_id: "PATRANG", display_name: "Bima" };
const receiver = { id: "U2", default_branch_id: "MASTRIP", display_name: "Rahmat" };
const baseSeed = (stock = 100) => ({
  Branch: [{ id: "PATRANG", code: "PTR", name: "Patrang", is_active: true }, { id: "MASTRIP", code: "MST", name: "Mastrip", is_active: true }],
  UserBranch: [{ id: "UB1", user_id: "U1", branch_id: "PATRANG", status: "active", is_default: true, can_create: true, can_edit: true, can_approve: true, can_post: true, can_cancel: true }, { id: "UB2", user_id: "U2", branch_id: "MASTRIP", status: "active", is_default: true, can_view: true }],
  Product: [{ id: "P1", sku: "IZZI", name: "IZZI Taro", unit: "pcs", is_active: true }, { id: "P2", sku: "DEV", name: "Device", unit: "pcs", is_active: true }],
  StockBalance: [{ id: "SB1", branch_id: "PATRANG", product_id: "P1", balance_scope: "branch", quantity: stock, created_date: "2026-01-01" }, { id: "SB2", branch_id: "MASTRIP", product_id: "P1", balance_scope: "branch", quantity: 50, created_date: "2026-01-01" }],
});
const draftPayload = (overrides = {}) => ({ date: "2026-08-14", source_branch_id: "MASTRIP", destination_branch_id: "MASTRIP", notes: "Test", items: [{ product_id: "P1", qty: 20 }], ...overrides });
const createDraft = (db, payload = draftPayload()) => saveTransferDraft({ payload, user: sourceUser, db });

test("A - draft changes no stock and creates no ledger", async () => { const db = database(baseSeed()); const result = await createDraft(db); assert.equal(result.transfer.status, "draft"); assert.equal(db.__stores.StockBalance[0].quantity, 100); assert.equal((db.__stores.StockLedger || []).length, 0); });
test("B - edit draft updates destination/items without stock movement", async () => { const db = database(baseSeed()); const first = await createDraft(db); const result = await createDraft(db, draftPayload({ transfer_id: first.transfer.id, items: [{ product_id: "P1", qty: 12 }] })); assert.equal(result.transfer.items[0].qty, 12); assert.equal(db.__stores.StockBalance[0].quantity, 100); assert.equal((db.__stores.StockLedger || []).length, 0); });
test("C - approve decreases source, sets transit, and creates one negative out ledger", async () => { const db = database(baseSeed()); const draft = await createDraft(db); const result = await approveTransfer({ payload: { transfer_id: draft.transfer.id, approval_request_id: "A1" }, user: sourceUser, db }); assert.equal(result.transfer.status, "approved"); assert.equal(result.transfer.items[0].in_transit_qty, 20); assert.equal(db.__stores.StockBalance.find((row) => row.id === "SB1").quantity, 80); assert.equal(db.__stores.StockBalance.find((row) => row.id === "SB2").quantity, 50); assert.equal(db.__stores.StockLedger[0].quantity, -20); });
test("D - insufficient stock leaves draft, balances, and ledger untouched", async () => { const db = database(baseSeed(10)); const draft = await createDraft(db); await assert.rejects(() => approveTransfer({ payload: { transfer_id: draft.transfer.id, approval_request_id: "A1" }, user: sourceUser, db }), (error) => error instanceof TransferError && error.code === "INSUFFICIENT_STOCK"); assert.equal(db.__stores.StockTransfer[0].status, "draft"); assert.equal(db.__stores.StockBalance[0].quantity, 10); assert.equal((db.__stores.StockLedger || []).length, 0); });
test("E - multi-item prevalidation prevents partial approval", async () => { const seed = baseSeed(); seed.StockBalance.push({ id: "SB3", branch_id: "PATRANG", product_id: "P2", balance_scope: "branch", quantity: 5 }); const db = database(seed); const draft = await createDraft(db, draftPayload({ items: [{ product_id: "P1", qty: 20 }, { product_id: "P2", qty: 10 }] })); await assert.rejects(() => approveTransfer({ payload: { transfer_id: draft.transfer.id, approval_request_id: "A1" }, user: sourceUser, db }), { code: "INSUFFICIENT_STOCK" }); assert.deepEqual(db.__stores.StockBalance.filter((row) => row.branch_id === "PATRANG").map((row) => row.quantity), [100, 5]); assert.equal((db.__stores.StockLedger || []).length, 0); });
test("F - full receive increases destination and clears transit", async () => { const db = database(baseSeed()); const draft = await createDraft(db); await approveTransfer({ payload: { transfer_id: draft.transfer.id, approval_request_id: "A1" }, user: sourceUser, db }); const result = await receiveTransfer({ payload: { transfer_id: draft.transfer.id, receiving_request_id: "R1", items: [{ product_id: "P1", received_qty: 20 }] }, user: receiver, db }); assert.equal(result.transfer.status, "received"); assert.equal(result.transfer.items[0].received_qty, 20); assert.equal(result.transfer.items[0].difference_qty, 0); assert.equal(result.transfer.items[0].in_transit_qty, 0); assert.equal(db.__stores.StockBalance.find((row) => row.id === "SB2").quantity, 70); });
test("G - physical partial receive posts 18 and records difference 2", async () => { const db = database(baseSeed()); const draft = await createDraft(db); await approveTransfer({ payload: { transfer_id: draft.transfer.id, approval_request_id: "A1" }, user: sourceUser, db }); const result = await receiveTransfer({ payload: { transfer_id: draft.transfer.id, receiving_request_id: "R1", items: [{ product_id: "P1", received_qty: 18 }] }, user: receiver, db }); assert.equal(result.transfer.items[0].received_qty, 18); assert.equal(result.transfer.items[0].difference_qty, 2); assert.equal(result.transfer.items[0].in_transit_qty, 0); assert.equal(db.__stores.StockBalance.find((row) => row.id === "SB2").quantity, 68); assert.equal(db.__stores.StockLedger.find((row) => row.movement_type === "transfer_in").quantity, 18); });
test("H - wrong branch cannot receive", async () => { const db = database(baseSeed()); const draft = await createDraft(db); await approveTransfer({ payload: { transfer_id: draft.transfer.id, approval_request_id: "A1" }, user: sourceUser, db }); await assert.rejects(() => receiveTransfer({ payload: { transfer_id: draft.transfer.id, receiving_request_id: "R1", items: [{ product_id: "P1", received_qty: 20 }] }, user: sourceUser, db }), { code: "UNAUTHORIZED_RECEIVER" }); });
test("I - approval retry is idempotent with one out ledger", async () => { const db = database(baseSeed()); const draft = await createDraft(db); const payload = { transfer_id: draft.transfer.id, approval_request_id: "SAME" }; await approveTransfer({ payload, user: sourceUser, db }); const retry = await approveTransfer({ payload, user: sourceUser, db }); assert.equal(retry.idempotent, true); assert.equal(db.__stores.StockLedger.filter((row) => row.movement_type === "transfer_out").length, 1); });
test("J - receive retry is idempotent with one in ledger", async () => { const db = database(baseSeed()); const draft = await createDraft(db); await approveTransfer({ payload: { transfer_id: draft.transfer.id, approval_request_id: "A1" }, user: sourceUser, db }); const payload = { transfer_id: draft.transfer.id, receiving_request_id: "SAME", items: [{ product_id: "P1", received_qty: 20 }] }; await receiveTransfer({ payload, user: receiver, db }); const retry = await receiveTransfer({ payload, user: receiver, db }); assert.equal(retry.idempotent, true); assert.equal(db.__stores.StockLedger.filter((row) => row.movement_type === "transfer_in").length, 1); });
test("K - frontend source injection is ignored", async () => { const db = database(baseSeed()); const result = await createDraft(db); assert.equal(result.transfer.source_branch_id, "PATRANG"); assert.equal(result.transfer.from_branch_id, "PATRANG"); });
test("L - new transfer UI and writes have no storage-location dependency", () => { for (const file of ["../src/pages/Mutasi.jsx", "../src/components/MutasiFormModal.jsx", "../src/components/ReceiveTransferModal.jsx"]) assert.doesNotMatch(fs.readFileSync(new URL(file, import.meta.url), "utf8"), /warehouse|gudang/i); });
test("M/N - card sees source only after approval and destination physical qty after receive", async () => { const db = database(baseSeed()); const draft = await createDraft(db); assert.equal((db.__stores.StockLedger || []).length, 0); await approveTransfer({ payload: { transfer_id: draft.transfer.id, approval_request_id: "A1" }, user: sourceUser, db }); assert.equal(buildBranchStockReadModel({ ledgerRows: db.__stores.StockLedger }).timelines.find((row) => row.branch_id === "PATRANG").qty_out, 20); assert.equal(db.__stores.StockLedger.some((row) => row.branch_id === "MASTRIP"), false); await receiveTransfer({ payload: { transfer_id: draft.transfer.id, receiving_request_id: "R1", items: [{ product_id: "P1", received_qty: 18 }] }, user: receiver, db }); assert.equal(buildBranchStockReadModel({ ledgerRows: db.__stores.StockLedger }).timelines.find((row) => row.branch_id === "MASTRIP").qty_in, 18); });
test("O - inventory source changes on approval and destination only on receive", async () => { const db = database(baseSeed()); const draft = await createDraft(db); await approveTransfer({ payload: { transfer_id: draft.transfer.id, approval_request_id: "A1" }, user: sourceUser, db }); assert.deepEqual(db.__stores.StockBalance.slice(0, 2).map((row) => row.quantity), [80, 50]); await receiveTransfer({ payload: { transfer_id: draft.transfer.id, receiving_request_id: "R1", items: [{ product_id: "P1", received_qty: 18 }] }, user: receiver, db }); assert.deepEqual(db.__stores.StockBalance.slice(0, 2).map((row) => row.quantity), [80, 68]); });
test("P - legacy transfer fields/status stay in schema and can be read", () => { const schema = fs.readFileSync(new URL("../base44/entities/StockTransfer.jsonc", import.meta.url), "utf8"); assert.match(schema, /from_warehouse_id/); assert.match(schema, /to_warehouse_id/); assert.match(schema, /"posted"/); });
test("Q - new core writes lifecycle only draft approved received and never forbidden status", () => { const core = fs.readFileSync(new URL("../base44/shared/stockTransferCore.ts", import.meta.url), "utf8"); assert.doesNotMatch(core, /status:\s*["']shipped["']|status:\s*["']posted["']/); assert.match(core, /status:\s*"draft"/); assert.match(core, /status:\s*"approved"/); assert.match(core, /status:\s*"received"/); });
test("approved transfer cannot be destructively deleted", async () => { const db = database(baseSeed()); const draft = await createDraft(db); await approveTransfer({ payload: { transfer_id: draft.transfer.id, approval_request_id: "A1" }, user: sourceUser, db }); await assert.rejects(() => deleteTransferDraft({ payload: { transfer_id: draft.transfer.id }, user: sourceUser, db }), { code: "INVALID_STATUS" }); assert.equal(db.__stores.StockTransfer.length, 1); });
