import React, { useEffect, useState } from "react";
import { receiveStockTransfer } from "@/lib/stockTransfer";
import { useToast } from "@/components/ui/use-toast";
import { Loader2, X } from "lucide-react";

export default function ReceiveTransferModal({ transfer, onClose, onSaved }) {
  const { toast } = useToast();
  const [items, setItems] = useState([]); const [notes, setNotes] = useState(""); const [submitting, setSubmitting] = useState(false);
  const [requestId, setRequestId] = useState(() => crypto.randomUUID());
  useEffect(() => { setItems((transfer?.items || []).map((row) => ({ product_id: row.product_id, product_name: row.product_name, approved_qty: Number(row.approved_qty ?? row.qty ?? 0), received_qty: Number(row.approved_qty ?? row.qty ?? 0) }))); setNotes(""); setRequestId(crypto.randomUUID()); }, [transfer]);
  if (!transfer) return null;
  const confirm = async () => { setSubmitting(true); try { await receiveStockTransfer({ transfer_id: transfer.id, receiving_request_id: requestId, receiving_notes: notes, items }); toast({ title: "Penerimaan mutasi berhasil" }); await onSaved?.(); onClose(); } catch (error) { toast({ title: "Penerimaan gagal", description: `${error.code || "INVALID_TRANSFER"}: ${error.message}`, variant: "destructive" }); } finally { setSubmitting(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/50" onClick={onClose} /><div className="relative w-full max-w-2xl rounded-2xl border bg-card shadow-2xl"><div className="flex items-center justify-between border-b px-6 py-4"><div><h2 className="text-lg font-semibold">Penerimaan Mutasi</h2><p className="text-xs text-muted-foreground">{transfer.transfer_number || transfer.code} · Dari {transfer.source_branch_name || transfer.from_branch_name}</p></div><button onClick={onClose}><X className="h-5 w-5" /></button></div><div className="space-y-4 p-6"><div className="overflow-hidden rounded-xl border"><table className="w-full text-sm"><thead><tr className="bg-muted/50 text-left"><th className="px-4 py-3">Produk</th><th className="px-4 py-3 text-right">Dikirim</th><th className="px-4 py-3">Diterima</th></tr></thead><tbody>{items.map((item, index) => <tr key={item.product_id} className="border-t"><td className="px-4 py-3 font-medium">{item.product_name}</td><td className="px-4 py-3 text-right">{item.approved_qty}</td><td className="px-4 py-3"><input type="number" min="0" max={item.approved_qty} value={item.received_qty} onChange={(event) => setItems((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, received_qty: Number(event.target.value) } : row))} className="w-28 rounded-lg border px-3 py-2" /></td></tr>)}</tbody></table></div><label><span className="mb-1 block text-sm font-medium">Catatan Penerimaan</span><textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={3} className="w-full rounded-lg border px-3 py-2" /></label><div className="flex justify-end gap-2"><button onClick={onClose} className="rounded-lg border px-4 py-2 text-sm">Batal</button><button onClick={confirm} disabled={submitting} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50">{submitting && <Loader2 className="h-4 w-4 animate-spin" />}Konfirmasi Penerimaan</button></div></div></div></div>;
}
